### ISSUE TITLE
Commands such as +hug and such get messed up when there is markup in user/nicknames.

### ISSUE THREAD

**Issue by lightinasnowstorm** [DrDevinRX/KawaiiBot2#1]
Markdown is rendered into certain commands, making them look bad and not match what discord does for username.
` is already escaped, _, *, > need to be fixed.

**Comment by DrDevinRX** [comment]
\>  = 0x1433 (ᐳ)

**Comment by DrDevinRX** [comment]
\* = ⁎

**Comment by DrDevinRX** [comment]
_ =  
there is a char there

**Comment by lightinasnowstorm** [comment]
All of these have been added, and there is no more markup rendering as of 87cc655. I think.
